### ISSUE TITLE
「問題一覧へ」から遷移すると移動ができなくなる

### ISSUE THREAD

**Issue by Chaha1n** [NIT-ToyotaC-19s/CTT#18]
/index下部の「問題一覧へ」ボタンから/catalogへ移動すると、ハンバーガーメニューから出したページ遷移ボタンが押せない問題を確認しました。

OS:Android 10(One UI 2.0)
Browser:Chrome 86.0.4240.110

**Comment by lemon-0451** [comment]
safariでもなった

**Comment by nono-n1I** [comment]
これ，ブラウザでリロードすると発生するのかもしれない(問題一覧と問題のページでだけ)
