### ISSUE TITLE
解答送信後，正解の選択肢を表示させる

### ISSUE THREAD

**Issue by nono-n1I** [NIT-ToyotaC-19s/CTT#25]
正解か不正解かと解説しか書いてないから，正解の選択肢を表示させたい

**Comment by nono-n1I** [comment]
正解の選択肢の表示を永続化させるの，ローカルストレージ使うか解説に書いちゃうかの2択なんだけどフロントで解答を保持するのはよろしくない...???

**Comment by Chaha1n** [comment]
別にいいんじゃない 再チャレンジできるわけじゃないし(よね)

**Comment by nono-n1I** [comment]
解説に直接書いた
